name: ci

on:
  push:
    branches:
      - master
      - gh_test_ci
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        GO_VERSION: ["1.16", "1.17"]
    env:
      GO_VERSION: ${{ matrix.GO_VERSION }}
    steps:
      -
         name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v1
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Build
        run: |
          docker buildx bake
      -
        name: Test
        run: |
          docker buildx bake test
      -
        name: Linters
        run: |
          docker buildx bake lint validate-gomod validate-shfmt
      -
        name: Cross
        run: |
          docker buildx bake cross

  test-freebsd-amd64:
    runs-on: macos-latest
    env:
      VAGRANT_VAGRANTFILE: hack/Vagrantfile.freebsd13
    steps:
      - name: Cache Vagrant boxes
        uses: actions/cache@v2
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ hashFiles('hack/Vagrantfile.freebsd13') }}
          restore-keys: |
            ${{ runner.os }}-vagrant-
      - uses: actions/checkout@v2
      - name: Set up vagrant
        run: vagrant up
      - name: "Run unit tests"
        run: vagrant ssh -- "cd /vagrant; go test ./..."
